### ISSUE TITLE
pfscanV3 message when run with a single profile

### ISSUE THREAD

**Issue by gsn7** [sib-swiss/pftools3#15]
the following message is displayed when you run pfscanV3 with a single profile
"pfscanV3 is not meant to be used with a single profile, use pfsearchV3 to get better performance in such case."
I would suggest this message should be prefixed with a '#' as pfsearchV3 continues to run and generates results.

**Comment by smoretti** [comment]
Hi
this message goes to **stderr**, like other error or warning messages.
It should not interfere with results that go to **stdout**.

I can add a '#' but redirect stdout in a file makes more sense for me.
This way only error and warning messages are visible directly on the screen.

**Comment by gsn7** [comment]
i  noticed that it sends the message to **stderr** after i had created the issue. thanks
