### ISSUE TITLE
Please include src/C/config.h.cmake inside release tarball

### ISSUE THREAD

**Issue by tillea** [sib-swiss/pftools3#17]
Hi,
this file is missing from the release tarball.  Users who want to build the code themselves need to download it manually (as I need to do for the Debian package).
Kind regards, Andreas.

**Comment by smoretti** [comment]
Hi
I manually downloaded the last release tarball (v3.2.6), the master branch tarball, as well as the last release zip and the master branch zip, all contain the **src/C/config.h.cmake**.
Where and how do you get your release tarball?

**Comment by tillea** [comment]
On Mon, Nov 30, 2020 at 01:03:35AM -0800, smoretti wrote:
> Hi
> I manually downloaded the last release tarball (v3.2.6), the master branch tarball, as well as the last release zip and the master branch zip, all contain the **src/C/config.h.cmake**.
> Where and how do you get your release tarball?
Sorry, my fault.  When doing the Debian package I'm excluding some files.  There was a bug in the regular expressions which excluded also this file.
Sorry for the noise, Andreas.

**Comment by smoretti** [comment]
OK great to read that
